"""
Operations / resolution analytics -- kept completely separate from the
routing model. Resolution outcomes (final_team, transfers, resolved_at) are
never fed into the classifier as features; they are only used here to answer
operational questions like "which teams are busiest" and "where is routing
friction costing us money".

ops-policy.pdf §4 costs used throughout: Rs 305 per transfer, Rs 260 per
extra customer contact generated by a misroute, Rs 540 per technician visit,
Rs 3.2 lakh/year for the legacy bot licence.
"""
from __future__ import annotations

import pandas as pd

from src.data import build_training_frame, canonicalize_team, load_raw

COST_PER_TRANSFER = 305
COST_PER_EXTRA_CONTACT = 260


def workload_by_team(df: pd.DataFrame) -> pd.DataFrame:
    """Volume actually closed by each team (final_team), i.e. real workload."""
    return (
        df.groupby("final_team").size().rename("requests_closed").reset_index()
        .sort_values("requests_closed", ascending=False)
    )


def routing_friction(df: pd.DataFrame) -> dict:
    """Quantify the cost of the legacy bot's misrouting, using ops-policy.pdf figures."""
    misrouted = (df["team_label"] != df["final_team"]).sum()
    total = len(df)
    transfer_cost = df["transfers"].sum() * COST_PER_TRANSFER
    extra_contact_cost = misrouted * COST_PER_EXTRA_CONTACT  # ops policy: ~1 extra contact per misroute
    return {
        "total_requests": int(total),
        "misrouted_by_legacy_bot": int(misrouted),
        "misroute_rate": round(misrouted / total, 4),
        "total_transfers": int(df["transfers"].sum()),
        "estimated_transfer_cost_inr": int(transfer_cost),
        "estimated_extra_contact_cost_inr": int(extra_contact_cost),
        "estimated_total_friction_cost_inr": int(transfer_cost + extra_contact_cost),
    }


def transfers_by_first_team(df: pd.DataFrame) -> pd.DataFrame:
    """Where the legacy bot's initial guess (team_label) most often needed a transfer."""
    g = df.groupby("team_label").agg(
        requests=("request_id", "count"),
        transferred=("transfers", lambda s: (s > 0).sum()),
    ).reset_index()
    g["transfer_rate"] = (g["transferred"] / g["requests"]).round(4)
    return g.sort_values("transfer_rate", ascending=False)


def monthly_volume(df: pd.DataFrame) -> pd.DataFrame:
    tmp = df.copy()
    tmp["month"] = tmp["created_at_ist"].dt.to_period("M").astype(str)
    return tmp.groupby(["month", "final_team"]).size().rename("count").reset_index()


def resolution_time_hours(df: pd.DataFrame, res: pd.DataFrame) -> pd.DataFrame:
    """Approximate resolution time in hours, with the legacy-Zoho UTC caveat applied.

    ops-policy.pdf §9: timestamps are IST except resolution events imported
    from the legacy Zoho event log, which were stored in UTC and never
    converted. We add 5:30 back to resolved_at for legacy_zoho-source rows
    only, so elapsed-time analytics aren't silently wrong for ~40% of the
    history. This is a best-effort correction documented as an assumption
    in reports/validation_report.md -- it is not applied anywhere in the
    routing model itself.
    """
    merged = df.merge(res[["request_id", "resolved_at"]], on="request_id", how="left")
    is_legacy = merged["source"] == "legacy_zoho"
    resolved_ist = merged["resolved_at"].copy()
    resolved_ist.loc[is_legacy] = merged.loc[is_legacy, "resolved_at"] + pd.Timedelta(hours=5, minutes=30)
    merged["resolved_at_ist_corrected"] = resolved_ist
    merged["resolution_hours"] = (
        (merged["resolved_at_ist_corrected"] - merged["created_at_ist"]).dt.total_seconds() / 3600.0
    )
    # Negative values would indicate a correction problem or bad data; clip for reporting sanity.
    merged.loc[merged["resolution_hours"] < 0, "resolution_hours"] = None
    return merged


def build_ops_summary(data_dir: str = "data") -> dict:
    df = build_training_frame(data_dir)
    _, res, _ = load_raw(data_dir)
    return {
        "workload_by_team": workload_by_team(df),
        "friction": routing_friction(df),
        "transfers_by_first_team": transfers_by_first_team(df),
        "monthly_volume": monthly_volume(df),
        "resolution_times": resolution_time_hours(df, res),
    }
